config/routes.rb
Rails.application.routes.draw do
  resources :items do
    member do
      put :move, :clone
    end
  end
  resources :schedules do
    resources :lists
  end
  get 'schedule_pick', to: 'schedules#schedule_pick'
  devise_for :users
  root 'schedules#index'
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  has_many :lists
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  #load_and_authorize_resource

  def index
    @schedule_source = Schedule.first
    @schedules = Schedule.all.where(entry_date: Time.zone.today.all_week) #오늘을 포함하는 주 schedules

    @mondays=[]
    Schedule.all.each do |schedule|
      if schedule.entry_date.monday?
        @mondays << schedule.entry_date
      end
    end

  end

  def create
    if !Schedule.all.where(entry_date: Time.zone.today.next_week.all_week).present?
      #for i in 0..4
        #s=Schedule.create(entry_date: Time.zone.today.next_week + i)
        #for i in 1..6
          #s.lists.create(name: "#{i}교시", period: i, floor: 3)
        #end
        #for i in 1..6
          #s.lists.create(name: "#{i}교시", period: i, floor: 4)
        #end
      #end

      for i in 0..4
        s=Schedule.create(entry_date: Time.zone.today.next_week + i)
        for j in 1..6
          if j == 6 and i != 1
            List.create(name: "#{j}교시", schedule: s, period: j, floor: 3, activated: false)
          else
            List.create(name: "#{j}교시", schedule: s, period: j, floor: 3, activated: true)
          end
        end
        for j in 1..6
          if j == 6 and i != 1
            List.create(name: "#{j}교시", schedule: s, period: j, floor: 4, activated: false)
          else
            List.create(name: "#{j}교시", schedule: s, period: j, floor: 4, activated: true)
          end
        end
      end

      respond_to do |format|
        format.html { redirect_to schedules_url, notice: "다음 주 스케줄 추가 성공!" }
      end
    else
      respond_to do |format|
        format.html { redirect_to schedules_url, notice: "이미 다음 주 스케줄이 있는디?" }
      end
    end
  end

  def schedule_pick
    if params.has_key?(:beginning_of_the_week)
      @monday = params[:beginning_of_the_week].to_date
    else
      @monday = Tome.zone.today.monday
    end
    @schedule_source = Schedule.first
    @schedules = Schedule.all.where(entry_date: @monday.all_week)
    @mondays=[]
    Schedule.all.each do |schedule|
      if schedule.entry_date.monday?
        @mondays << schedule.entry_date
      end
    end
  end
end

app/views/schedules/_schedule.html.erb
<div class="col schedule" style="width: 340px; border-style: solid; border-width: 1px; border-color: blue; text-align:center;">
  <div class="row mt-3" style="text-align: center;">
    <h3>
      <% if schedule.entry_date.today? %>
        <%= schedule.entry_date.month.to_s + "월 " + schedule.entry_date.day.to_s + "일  " + schedule.entry_date.strftime("%a")%><span style="color: red;">  오늘</span>
      <% else %>
        <%= schedule.entry_date.month.to_s + "월 " + schedule.entry_date.day.to_s + "일  " + schedule.entry_date.strftime("%a") %>
      <% end %>
    </h3>
  </div><!-- row -->

  <div class="row row-cols-2 mb-3">
    <div class="col floor3" style="text-align: center;">
      <h5>3층</h5>
      <% schedule.lists.each do |list| %>
        <% if list.floor == 3 and list.activated == true %>
          <%= render list %>
        <% end %>
      <% end %>
    </div><!-- col floor3 -->

    <div class="col floor4" style="text-align: center;">
      <h5>4층</h5>
      <% schedule.lists.each do |list| %>
        <% if list.floor == 4 and list.activated == true %>
          <%= render list %>
        <% end %>
      <% end %>
    </div><!-- col floor4 -->
  </div><!-- row row-cols-2 -->
</div><!-- col schedule -->

app/views/schedules/_todo.html.erb
<div class="todo" style="width: 1090px; flex: 0 0 1090px; height: 300px; border: solid;">
  <div class="todo head" style="display: flex; padding: 10px;">
    <div>
      <h3>
        <%= schedule_source.lists.first.name %>
      </h3>
    </div>
    <!--
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Launch demo modal
    </button>
    -->
    <div style="margin-left: auto;">
      <% if can? :manage, Item %>
        <%= link_to "Create", new_item_path, class: "btn btn-primary", data: { turbo_frame: :modal } %>
      <% end %>
    </div>
  </div><!-- todo head -->

  <%= turbo_frame_tag :modal %>

  <%= turbo_frame_tag "items" do %>
    <div id="group_source" class="items" data-controller="sortable" data-sortable-group-value="items" data-sortable-item-list-id="1" style="display: flex; flex-wrap: wrap;">
      <% schedule_source.lists.first.items.rank(:row_order).each do |item| %>
        <%= render "/items/source_item", item: item %>
      <% end %>
    </div><!-- group_source -->
  <% end %>
</div><!-- todo -->

app/views/schedules/index.html.erb
<p style="color: green"><%= notice %></p>

<div class="main">
  <div class="row" style="display: flex; justify-content: center;">
    <%= render "todo", schedule_source: @schedule_source %>
  </div><!-- row -->

  <div class="row row-cols-5 mt-1" style="display:flex; justify-content: center;">
    <% @schedules.each do |schedule| %>
      <%= render schedule %>
    <% end %>
  </div> <!-- row row-cols-5 -->

  <%= render "shared/admin" %>
</div><!-- schedule -->

app/views/schedules/schedule_pick.html.erb
<div class="main">
  <div class="row" style="display: flex; justify-content: center;">
    <%= render "todo", schedule_source: @schedule_source %>
  </div><!-- row -->

  <div class="row row-cols-5 mt-1" style="display:flex; justify-content: center;">
    <% @schedules.each do |schedule| %>
      <%= render schedule %>
    <% end %>
  </div> <!-- row row-cols-5 -->

  <%= render "shared/admin" %>
</div>