config/routes.rb
Rails.application.routes.draw do
  resources :items do
    member do
      put :move, :clone
    end
  end
  resources :schedules do
    resources :lists
  end
  get 'schedule_pick', to: 'schedules#schedule_pick'
  devise_for :users
  root 'schedules#index'
end

app/views/shared/_admin.html.erb
<% if user_signed_in? and can? :manage, Schedule %>
  <div class="row mt-1">
    <div class="mt-5 ms-5">
      <%= link_to "New schedules", schedules_path, class: "btn btn-info", data: { turbo_method: :post } %>
    </div>
    <div class="mt-1">
      <% @mondays.each do |monday| %>
        <div class="mt-1 ms-5">
          <!-- 이렇게 비교가 안 되는 거 같다 -->
          <!--
          <%# if monday.to_time == Time.zone.today.monday %>
            이번 주
          <%# else %>
            <%#= monday.all_week %>
          <%# end %>
          -->

          <%= link_to "#{monday.strftime('%Y-%m-%d')}~#{monday.days_since(4).strftime('%Y-%m-%d')}", schedule_pick_path(beginning_of_the_week: monday) %>
        </div>
      <% end %>

    </div>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="container-fluid">
  <nav class="navbar navbar-expand-md navbar-light bg-light">
    <div class="container mx-auto">
      <%= link_to root_path, class: "navbar-brand" do %>
       아라초4학년
      <% end %>

      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <%= link_to "Home", root_path, class: "nav-link active" %>
            <!--
            <a class="nav-link active" aria-current="page" href="root_path">Home</a>
            -->
          </li>

          <!--
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              Dropdown
            </a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#">Action</a></li>
              <li><a class="dropdown-item" href="#">Another action</a></li>
              <li><hr class="dropdown-divider"></li>
              <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
          </li>
          -->
        </ul>

        <ul class="navbar-nav">
          <% if user_signed_in? %>
            <%= yield :right_nav %>

            <li class="nav-item dropdown">
              <a href="#" class="nav-link dropdown-toggle" data-bs-toggle="dropdown" role="button" aria-expanded="false">
                <%= current_user.username %> <span class="caret"></span>
              </a>
              <ul class="dropdown-menu dropdown-menu-end">
                <li><%= link_to "Settings", edit_user_registration_path, class: "dropdown-item" %></li>
                <li><hr class="dropdown-divider"></li>
                <li><%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %></li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "Sign Up", new_user_registration_path, class: "btn btn-outline-success me-2" %></li>
            <li><%= link_to "Login", new_user_session_path, class: "btn btn-outline-secondary" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </nav>

</div>