config/routes.rb
Rails.application.routes.draw do
  resources :items do
    member do
      put :move, :clone
    end
  end
  resources :schedules do
    resources :lists
  end
  get 'schedule_pick', to: 'schedules#schedule_pick'
  devise_for :users
  root 'schedules#index'
end

app/models/item.rb
class Item < ApplicationRecord
  validates :body, presence: true

  belongs_to :list
  belongs_to :user

  include RankedModel
  ranks :row_order, with_same: :list_id
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: %i[ edit update destroy ]
  #before_action :set_item, only: %i[ destroy ]

  load_and_authorize_resource

  def move
    #debugger
    @item = Item.find(params[:id])
    @item.update(row_order_position: params[:row_order_position], list_id: params[:list_id])
    head :no_content
  end

  def clone
    #debugger
    @item_source = Item.find(params[:sortable_item_id])
    @item = Item.new(
      list_id: params[:list_id],
      user: current_user,
      name: @item_source.name + "(" + current_user.username + ")",
      body: @item_source.body,
      color: @item_source.color,
      row_order_position: params[:row_order_position]
    )
    #debugger
    @item.save
    head :no_content
  end

  def new
    @item = Item.new
  end

  def create
    @item = Item.new(item_params)
    @item.list_id = 1
    @item.user = current_user
    @item.color = random_color

    respond_to do |format|
      if @item.save
        format.html { redirect_to schedules_url, notice: "item 생성 성공!" }
        format.turbo_stream
      else
        format.html { redirect_to schedules_url, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @item.update(item_params)
        format.turbo_stream do
          render turbo_stream: turbo_stream.update("item_#{@item.id}", partial: "/items/source_item", locals: { item: @item })
        end
        format.html { redirect_to schedules_url, notice: "Item was successfully updated." }
      else
        format.html { redirect_to schedules_url, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @item.destroy!
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: "삭제 성공!" }
      #format.turbo_stream
    end
  end

  private
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:body, :name)
    end

    def random_color
      floor=22
      r=(rand(256-floor)+floor).to_s 16
      g=(rand(256-floor)+floor).to_s 16
      b=(rand(256-floor)+floor).to_s 16
      color=[r,g,b].map{|h|h.rjust 2,'0'}.join
      puts "##############################################################################"
      puts color
      puts "##############################################################################"
      color
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<%= form_with(model: item) do |form| %>
  <% if item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
        <% item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :body, style: "display: block" %>
    <%= form.text_field :body %>
  </div>

  <div class="mt-2" data-controller="modals">
    <%= form.submit %>
    <%#= form.submit data: { action: "turbo:submit-end->modals#submitEnd" } %>
    <%= link_to "Cancel", "#",
      data: { action: "modals#close"},
      class: "btn btn-danger" %>
  </div>
<% end %>

app/views/items/_item.html.erb
<div id="<%= dom_id item %>" class="item" data-sortable-item-id="<%= item.id %>" data-sortable-item-user-id="<%= item.user.id %>">
  <div class="item__body" style="width: 120px; margin: 5px; padding: 5px; border-radius: 5px; cursor: pointer; align-items: center; display: flex; background-color: #<%= item.color %>;">
    <div class="item__info">
      <%= item.name %>
    </div><!-- item__info -->
    <div class="item__buttons" style="margin-left: auto; display: flex;">
      <% if can? :destroy, item %>
        <%= link_to item_path(item), data: { turbo_method: :delete } do %>
          <i class="fa fa-times-circle" style="color: red;"></i>
        <% end %>
      <% end %>
    </div><!-- item__buttons -->
  </div><!-- item__body -->
</div><!-- item -->

app/views/items/_source_item.html.erb
<div id="<%= dom_id item %>" class="item" data-sortable-item-id="<%= item.id %>" data-sortable-item-user-id="<%= item.user.id %>">
  <div class="item__body" style="width: 200px; margin: 5px; padding: 5px; border-radius: 5px; cursor: pointer; align-items: center; display: flex; background-color: #<%= item.color %>;">
    <div class="item__info">
      <%= item.name %>
      <%= item.body %>
    </div><!-- item__info -->
    <div class="item__buttons" style="margin-left: auto; display: flex;">
      <% if can? :edit, item %>
        <%= link_to edit_item_path(item), data: { turbo_frame: :modal } do %>
          <i class="fa fa-pen-to-square" style="color: black; margin-right: 5px;"></i>
        <% end %>
      <% end %>
      <% if can? :destroy, item %>
        <%= link_to item_path(item), data: { turbo_method: :delete } do %>
          <i class="fa fa-times-circle" style="color: red;"></i>
        <% end %>
      <% end %>
    </div><!-- item__buttons -->
  </div><!-- item__body -->
</div><!-- item -->

app/views/items/create.turbo_stream.erb
<%= turbo_stream.append "group_source" do %>
  <%= render "/items/source_item", item: @item %>
<% end %>
<%= turbo_stream.update Item.new, "" %>

app/views/items/edit.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="modals">
    <div class="modal-custom" data-action="turbo:submit-end->modals#submitEnd">
      <%= render "form", item: @item %>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<%= turbo_frame_tag :modal do %>
  <div data-controller="modals">
    <div class="modal-custom" data-action="turbo:submit-end->modals#submitEnd">
      <%= render "form", item: @item %>
    </div>
  </div>
<% end %>